# Generated by Django 4.2.7 on 2023-12-31 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispenser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispenser_id', models.CharField(max_length=100, unique=True)),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dispensador',
                'verbose_name_plural': 'Dispensadores',
            },
        ),
        migrations.CreateModel(
            name='DispenserProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispenser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dispensers.dispenser')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
        migrations.AddField(
            model_name='dispenser',
            name='products',
            field=models.ManyToManyField(through='dispensers.DispenserProducts', to='products.product'),
        ),
        migrations.AddField(
            model_name='dispenser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
