# Generated by Django 4.2.7 on 2024-01-08 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0021_remove_analysis_pendiente_analysis_realizado_and_more'),
        ('products', '0002_rename_presentacion_presentation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActiveProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('remaining_days', models.PositiveIntegerField(default=0)),
                ('prescription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.prescription')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
