# Generated by Django 4.2.7 on 2024-01-08 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0021_remove_analysis_pendiente_analysis_realizado_and_more'),
        ('medication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activeproduct',
            old_name='active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='activeproduct',
            old_name='product',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='activeproduct',
            old_name='remaining_days',
            new_name='recordatorio',
        ),
        migrations.RemoveField(
            model_name='activeproduct',
            name='prescription',
        ),
        migrations.AddField(
            model_name='activeproduct',
            name='prescripcion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='consultations.prescription'),
        ),
    ]
