# Generated by Django 4.2.7 on 2023-12-16 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='biografia',
        ),
        migrations.AddField(
            model_name='profile',
            name='apellido',
            field=models.TextField(default='', verbose_name='Apellido'),
        ),
        migrations.AddField(
            model_name='profile',
            name='historial',
            field=models.TextField(default='', verbose_name='Historial'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nombre',
            field=models.TextField(default='', verbose_name='Nombre'),
        ),
    ]
