# Generated by Django 4.2.7 on 2023-12-16 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_biografia_profile_apellido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Perfíl', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='nombre',
        ),
    ]
