# Generated by Django 4.2.7 on 2024-01-16 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_requestpatient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestpatient',
            name='aceptada',
        ),
        migrations.AddField(
            model_name='requestpatient',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10),
        ),
    ]
