# Generated by Django 4.2.7 on 2024-01-18 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_patientprofile_medico_patientprofile_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='familyprofile',
            name='paciente',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Paciente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familiares', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
        ),
    ]
