# Generated by Django 4.2.7 on 2024-01-19 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_familyprofile_paciente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familyprofile',
            name='parentezco',
        ),
        migrations.AddField(
            model_name='requestpatient',
            name='parentezco',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Parentezco'),
        ),
    ]
