# Generated by Django 4.2.7 on 2024-01-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_careprofile_comentario_careprofile_disponibilidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
