# Generated by Django 4.2.7 on 2024-01-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='precio_compra',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Precio de Compra'),
        ),
    ]
