# Generated by Django 4.2.7 on 2024-01-02 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_presentacion_presentation_and_more'),
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.specialty', verbose_name='Especialidad'),
        ),
    ]
