# Generated by Django 4.2.7 on 2024-01-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_alter_doctor_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='motivo',
            field=models.TextField(blank=True, verbose_name='Motivo'),
        ),
    ]
