# Generated by Django 4.2.7 on 2024-01-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0003_appointment_motivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prescription',
            old_name='instrucciones',
            new_name='indicaciones',
        ),
        migrations.AddField(
            model_name='appointment',
            name='costo',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Costo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='pdf_indicaciones',
            field=models.FileField(blank=True, null=True, upload_to='prescription/', verbose_name='PDF de Indicaciones'),
        ),
    ]
