# Generated by Django 4.2.7 on 2024-01-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_rename_instrucciones_prescription_indicaciones_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctores'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Receta e Indicaciones', 'verbose_name_plural': 'Recetas e indicaciones'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='telefono_reservas1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='telefono_reservas2',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ubicacion_consultorio1',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='ubicacion_consultorio2',
        ),
        migrations.AddField(
            model_name='doctor',
            name='telefono_reserva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Reserva'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Personal'),
        ),
    ]
