# Generated by Django 4.2.7 on 2024-01-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_presentacion_presentation_and_more'),
        ('consultations', '0005_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='dosis',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='indicaciones',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='medicamentos',
        ),
        migrations.AddField(
            model_name='appointment',
            name='pendiente',
            field=models.BooleanField(default=True, verbose_name='Pendiente'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono_personal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='telefono_reserva',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Consultorio'),
        ),
        migrations.CreateModel(
            name='PrescriptionMedication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=255)),
                ('indicaciones', models.TextField()),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication', to='consultations.prescription')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Medicación de la Receta',
                'verbose_name_plural': 'Medicaciones de la Receta',
            },
        ),
    ]
