# Generated by Django 4.2.7 on 2024-01-03 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0007_remove_appointment_pedido_estudios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cita_posterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Días para la siguiente cita'),
        ),
    ]
