# Generated by Django 4.2.7 on 2024-01-03 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0008_alter_appointment_cita_posterior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita', 'verbose_name_plural': 'Citas'},
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='notas',
            new_name='nota',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='cita_posterior',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='estudios',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='medicamentos',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='otras_indicaciones',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.CreateModel(
            name='ConsultationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.BooleanField(default=False, verbose_name='Medicamentos')),
                ('estudio', models.BooleanField(default=False, verbose_name='Estudios')),
                ('cita_posterior', models.PositiveIntegerField(default=0, verbose_name='Días para la siguiente cita')),
                ('otras_indicaciones', models.BooleanField(default=False, verbose_name='Otras Indicaciones')),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='consultations.appointment', verbose_name='Cita')),
            ],
            options={
                'verbose_name': 'Detalle de Consulta',
                'verbose_name_plural': 'Detalles de Consultas',
            },
        ),
    ]
