# Generated by Django 4.2.7 on 2024-01-04 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0009_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.BooleanField(default=False, verbose_name='Medicamentos')),
                ('estudio', models.BooleanField(default=False, verbose_name='Estudios')),
                ('otras_indicaciones', models.BooleanField(default=False, verbose_name='Otras Indicaciones')),
            ],
            options={
                'verbose_name': 'Detalle de Consulta',
                'verbose_name_plural': 'Detalles de Consultas',
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='cita_posterior',
            field=models.PositiveIntegerField(default=0, verbose_name='Días para la siguiente cita'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='costo',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Costo'),
        ),
        migrations.DeleteModel(
            name='ConsultationDetails',
        ),
        migrations.AddField(
            model_name='consultation',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='consultations.appointment', verbose_name='Cita'),
        ),
    ]
