# Generated by Django 4.2.7 on 2024-01-04 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_presentacion_presentation_and_more'),
        ('consultations', '0010_consultation_appointment_cita_posterior_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Consulta', 'verbose_name_plural': 'Consultas'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'verbose_name': 'Prescripción', 'verbose_name_plural': 'Prescripciones'},
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='estudio',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='medicamento',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='otras_indicaciones',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='cita',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pdf_indicaciones',
        ),
        migrations.AddField(
            model_name='consultation',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='consultations/audios/', verbose_name='Audio de la Consulta'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='diagnostico',
            field=models.CharField(blank=True, max_length=255, verbose_name='Diagnóstico'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas de la Consulta'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='pdf_indicaciones',
            field=models.FileField(blank=True, null=True, upload_to='consultations/prescriptions/', verbose_name='PDF de Indicaciones'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dosis',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='duracion',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='frecuencia',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='indicaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='consultation',
            name='cita',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consulta', to='consultations.appointment', verbose_name='Cita'),
        ),
        migrations.DeleteModel(
            name='PrescriptionMedication',
        ),
    ]
