# Generated by Django 4.2.7 on 2024-01-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0012_remove_prescription_duracion_prescription_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='frecuencia',
            field=models.CharField(max_length=255, verbose_name='Frecuencia'),
        ),
    ]
