# Generated by Django 4.2.7 on 2024-01-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0013_alter_prescription_frecuencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='dosis',
            field=models.PositiveIntegerField(verbose_name='Dosis diaria'),
        ),
    ]
