# Generated by Django 4.2.7 on 2024-01-04 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0014_alter_prescription_dosis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='indicaciones',
        ),
    ]
