# Generated by Django 4.2.7 on 2024-01-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0015_remove_prescription_indicaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Activa'),
        ),
    ]
