# Generated by Django 4.2.7 on 2024-01-06 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0016_prescription_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='tipo',
            field=models.CharField(choices=[('consulta', 'Consulta Médica'), ('analisis', 'Análisis Médico')], default='consulta', max_length=10, verbose_name='Tipo de Cita'),
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_analisis', models.DateField(verbose_name='Fecha del Análisis')),
                ('resultado_pdf', models.FileField(blank=True, null=True, upload_to='analisis_resultados/', verbose_name='Resultado del Análisis')),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analisis', to='consultations.consultation', verbose_name='Consulta Relacionada')),
            ],
            options={
                'verbose_name': 'Análisis',
                'verbose_name_plural': 'Análisis',
            },
        ),
    ]
