# Generated by Django 4.2.7 on 2024-01-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0017_appointment_tipo_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Notas de la Consulta'),
        ),
    ]
