# Generated by Django 4.2.7 on 2024-01-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0018_analysis_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
    ]
