# Generated by Django 4.2.7 on 2024-01-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0020_analysis_pendiente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='pendiente',
        ),
        migrations.AddField(
            model_name='analysis',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='Realizado'),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='resultado_pdf',
            field=models.FileField(blank=True, null=True, upload_to='analysis/', verbose_name='Resultado del Análisis'),
        ),
    ]
