# Generated by Django 4.2.7 on 2024-01-11 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_presentacion_presentation_and_more'),
        ('consultations', '0021_remove_analysis_pendiente_analysis_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='products.product', verbose_name='Producto'),
        ),
    ]
