# Generated by Django 4.2.7 on 2024-01-23 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consultations', '0022_alter_prescription_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='analisis_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='citas_asociadas', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consultation',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='consultas_asociadas', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='doctores_asociados', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prescription',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones_asociadas', to=settings.AUTH_USER_MODEL, verbose_name='Paciente'),
            preserve_default=False,
        ),
    ]
