# Generated by Django 4.2.7 on 2024-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0024_analysis_creado_el_analysis_creado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='creado_el',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
