# Generated by Django 4.2.7 on 2023-12-31 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Especialidad',
                'verbose_name_plural': 'Especialidades',
            },
        ),
        migrations.CreateModel(
            name='Presentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Presentación',
                'verbose_name_plural': 'Presentaciones',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_local', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('existencia', models.PositiveBigIntegerField(verbose_name='Existencia en Inventario')),
                ('uso_cotidiano', models.BooleanField(default=True, verbose_name='Usado actualmente')),
                ('venta_controlada', models.BooleanField(default=False, verbose_name='Venta Controlada')),
                ('cantidad_caja', models.PositiveBigIntegerField(default=1, verbose_name='Cantidad por caja')),
                ('precio', models.PositiveBigIntegerField(default=0, verbose_name='Precio')),
                ('compuesto_principal', models.TextField(blank=True, max_length=100, verbose_name='Compuesto Principal')),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante')),
                ('pais', models.CharField(blank=True, default='Paraguay', max_length=50, verbose_name='País')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('usos', models.TextField(blank=True, verbose_name='Usos posibles')),
                ('posologia', models.TextField(blank=True, verbose_name='Posología')),
                ('embarazo', models.TextField(blank=True, verbose_name='Embarazo')),
                ('lactancia', models.TextField(blank=True, verbose_name='Lactancia')),
                ('contraindicaciones', models.TextField(blank=True, verbose_name='Contraindicaciones')),
                ('precauciones', models.TextField(blank=True, verbose_name='Precauciones')),
                ('reacciones_adversas', models.TextField(blank=True, verbose_name='Reacciones Adversas')),
                ('interacciones', models.TextField(blank=True, verbose_name='Interacciones')),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('imagen_caja', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('creado_el', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('especialidad', models.ManyToManyField(blank=True, to='products.especialidad')),
                ('presentacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.presentacion')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
