# Generated by Django 4.2.7 on 2024-01-02 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Presentacion',
            new_name='Presentation',
        ),
        migrations.RenameModel(
            old_name='Especialidad',
            new_name='Specialty',
        ),
    ]
